### ISSUE TITLE
Switsches are not working anymore

### ISSUE THREAD

**Issue by guenthersbuehli** [tefinger/hass-brematic#16]
**Describe the bug**
press button in dashboard causes no reaction other than
error:
Fehler beim Aufrufen des Diensts switch/turn_on. Detected that custom integration 'brematic' calls async_write_ha_state from a thread at custom_components/brematic/switch.py, line 242: self.async_write_ha_state(). Please report it to the author of the 'brematic' custom integration.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Home Assistant:**
 - Home Assistant Version: 
Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1
 - Brematic Component Version: 0.6.0

**Additional context**

**Comment by lines27** [comment]
I had the same problem when updating HA.
Since the code is obviously no longer maintained by the developers, I edited it manually in my HA.
I replaced self.async_write_ha_state() with self.schedule_update_ha_state() in lines 263 and 272 in the /homeassistant/custom_components/switch.py file.
Restart HA and it worked :-)
Maybe Tobias can also make these small changes here in Github in a new release.

**Comment by tefinger** [comment]
Already fixed in #15
